#!/bin/bash
KEYPATH=$HOME/projects/httpsnow/
echo https://localhost:44330/
echo https://localhost:44330/index.html
#openssl s_server -accept 44330 -cert ${KEYPATH}/server.crt -key ${KEYPATH}/server.key -WWW
python $KEYPATH/httpsnow.py --crt ${KEYPATH}/server.crt --key ${KEYPATH}/server.key 
